export const INDUSTRIES = [
  "Accounting",
  "Airlines/Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel & Fashion",
  "Architecture & Planning",
  "Arts & Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Biotechnology",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies and Equipment",
  "Business Supplies & Equipment",
  "Capital Markets",
  "Chemicals",
  "Civic & Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer & Network Security",
  "Computer Software",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense & Space",
  "Design",
  "Education Management",
  "E-learning",
  "Electrical & Electronic Manufacturing",
  "Electrical/Electronic Manufacturing",
  "Engineering",
  "Entertainment",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Fishery",
  "Food & Beverages",
  "Food Production",
  "Fundraising",
  "Furniture",
  "Gambling & Casinos",
  "Glass, Ceramics & Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design",
  "Health, Wellness & Fitness",
  "Higher Education",
  "Horticulture",
  "Hospital & Health Care",
  "Hospitality",
  "Human Resources",
  "Import & Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology and Services",
  "Information Technology & Services",
  "Insurance",
  "International Affairs",
  "International Trade & Development",
  "Internet",
  "Investment Banking",
  "Investment Management",
  "Judiciary",
  "Law Enforcement",
  "Law Practice",
  "Legal Services",
  "Legislative Office",
  "Leisure, Travel & Tourism",
  "Libraries",
  "Logistics & Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Marketing & Advertising",
  "Marketing and Advertising",
  "Market Research",
  "Mechanical Or Industrial Engineering",
  "Media Production",
  "Medical Device",
  "Medical Devices",
  "Medical Practice",
  "Mental Health Care",
  "Military",
  "Mining & Metals",
  "Mobile Games",
  "Motion Pictures & Film",
  "Museums & Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers",
  "Non-profit Organization Management",
  "Oil & Energy",
  "Online Media",
  "Outsourcing/Offshoring",
  "Package/Freight Delivery",
  "Packaging & Containers",
  "Paper & Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary/Secondary Education",
  "Printing",
  "Professional Training & Coaching",
  "Program Development",
  "Public Policy",
  "Public Relations & Communications",
  "Public Safety",
  "Publishing",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Recreational Facilities & Services",
  "Religious Institutions",
  "Renewables & Environment",
  "Research",
  "Restaurants",
  "Retail",
  "Security & Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Staffing and Recruiting",
  "Staffing & Recruiting",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation & Localization",
  "Transportation/Trucking/Railroad",
  "Utilities",
  "Venture Capital & Private Equity",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine & Spirits",
  "Wireless",
  "Writing & Editing"
]

export const TITLES = [
  "chief executive officer",
  "ceo",
  "president",
  "director of operations",
  "chief financial officer",
  "chief operating officer",
  "controller",
  "environment, health and safety manager",
  "chief medical officer",
  "founder & ceo",
  "cfo",
  "medical director",
  "vice president",
  "accounting manager",
  "partner",
  "owner",
  "engineering manager",
  "general dentist",
  "director",
  "co-founder",
  "founder and ceo",
  "senior software engineer",
  "vice president operations",
  "environmental health safety specialist",
  "dentist",
  "physician recruiter",
  "founder",
  "supply chain manager",
  "president and ceo",
  "president & ceo",
  "healthcare recruiter",
  "operations manager",
  "facility administrator",
  "devops engineer",
  "executive director",
  "co-founder & ceo",
  "director of finance",
  "site reliability engineer",
  "sales director",
  "--",
  "product manager",
  "ehs manager",
  "coo",
  "chief information security officer",
  "program coordinator",
  "product owner",
  "staff accountant",
  "human resources director",
  "vice president of operations",
  "finance manager",
  "head of product",
  "talent acquisition consultant",
  "president/ceo",
  "market research analyst",
  "board member",
  "project officer",
  "vice president of sales",
  "senior accountant",
  "managing director",
  "ceo & founder",
  "chief operations officer",
  "general manager",
  "senior site reliability engineer",
  "staff software engineer",
  "practice manager",
  "ceo & co-founder",
  "project manager",
  "assistant controller",
  "marketing manager",
  "chief marketing officer",
  "software engineering manager",
  "investment director",
  "finance director",
  "retired",
  "sales operations manager",
  "market researcher",
  "ceo and founder",
  "co-founder and ceo",
  "founder/ceo",
  "clinical manager",
  "market research manager",
  "senior devops engineer",
  "devops team lead",
  "devops manager",
  "managing partner",
  "physician",
  "manager",
  "recruiter",
  "chief human resources officer",
  "software engineer",
  "founder, ceo",
  "financial controller",
  "marketing director",
  "business owner",
  "senior packaging engineer",
  "chief technology officer",
  "associate director",
  "hse manager",
  "director of human resources",
  "principal",
  "talent development manager",
  "registered nurse",
  "chief clinical officer",
  "",
  "administrator",
  "ceo and co-founder",
  "occupational health and safety specialist",
  "eh&s manager",
  "senior vice president",
  "president and chief executive officer",
  "senior market research analyst",
  "vice president information security",
  "director of nursing",
  "care assistant",
  "member",
  "member board of directors",
  "senior project officer",
  "director of talent management",
  "revenue operations manager",
  "director of credit",
  "ehs specialist",
  "clinic manager",
  "director of marketing",
  "director of learning and development",
  "medical epidemiologist",
  "general assistant",
  "director of business development",
  "vice president marketing",
  "vp of operations",
  "vp",
  "vp of finance",
  "senior engineering manager",
  "director talent management",
  "team lead",
  "vice president human resources",
  "director, talent management",
  "co-founder & cto",
  "program director",
  "corporate controller",
  "senior product manager",
  "environmental, health and safety manager",
  "human resources manager",
  "executive vice president",
  "customer success manager",
  "learning consultant",
  "director of product development",
  "operations director",
  "ceo/founder",
  "dental practice owner",
  "market research",
  "vice president talent acquisition",
  "founder / ceo",
  "business operations manager",
  "md",
  "chief people officer",
  "director of devops",
  "health and safety specialist",
  "provider recruiter",
  "information security manager",
  "disease intervention specialist",
  "clinical director",
  "vice president of finance",
  "vice president finance",
  "director talent acquisition",
  "vp of sales",
  "chief investment officer",
  "office manager",
  "team leader",
  "practice administrator",
  "president & chief executive officer",
  "consultant",
  "director of clinical services",
  "environmental health and safety manager",
  "chief scientific officer",
  "business manager",
  "senior physician recruiter",
  "head of operations",
  "account manager",
  "accountant",
  "hr business partner",
  "senior market research manager",
  "director of sales",
  "psychiatric nurse practitioner",
  "bookkeeper",
  "loan officer",
  "chief of staff",
  "head of security",
  "real estate broker",
  "learning and development consultant",
  "vice president of business development",
  "talent management specialist",
  "security manager",
  "ciso",
  "chief administrative officer",
  "area manager",
  "public health nurse",
  "associate dentist",
  "president / ceo",
  "director of behavioral health",
  "head of research",
  "assistant marketing manager",
  "program manager",
  "regional director",
  "vp operations",
  "executive assistant",
  "regional director of operations",
  "chief information officer",
  "director of security",
  "director, human resources",
  "market research specialist",
  "healthcare assistant",
  "chief revenue officer (cro)",
  "retail marketing manager",
  "regional sales director",
  "packaging development manager",
  "vice president, information security",
  "chief security officer",
  "account executive",
  "business development manager",
  "senior recruiter",
  "health safety environment coordinator",
  "chairman",
  "vp of marketing",
  "environmental health and safety specialist",
  "co-founder, ceo",
  "senior human resources business partner",
  "environmental health safety",
  "director of clinical operations",
  "staff site reliability engineer",
  "site reliability engineering manager",
  "chief resident",
  "emergency medicine physician",
  "director of engineering",
  "market research consultant",
  "administrative director",
  "director of financial planning and analysis",
  "senior project manager",
  "founder & chief executive officer",
  "psychiatrist",
  "senior marketing manager",
  "talent acquisition specialist",
  "advisor",
  "director of business operations",
  "advisory board member",
  "occupational safety health specialist",
  "head of marketing",
  "financial analyst",
  "senior manager",
  "vice president, operations",
  "principal software engineer",
  "deputy manager",
  "chief growth officer",
  "senior consultant",
  "pediatrician",
  "product development manager",
  "store director",
  "regional medical director",
  "vice president, talent acquisition",
  "talent acquisition partner",
  "ceo ",
  "director of accounting",
  "vice president of marketing",
  "talent acquisition manager",
  "it manager",
  "hr director",
  "head of talent",
  "public health educator",
  "public health program manager",
  "ceo & president",
  "senior product owner",
  "senior vice president of sales",
  "ceo, co-founder",
  "clinical operations manager",
  "director of product management",
  "senior director",
  "nurse recruiter",
  "ceo and president",
  "chief strategy officer",
  "adjunct professor",
  "administrative assistant",
  "chief product officer",
  "head of devops",
  "vice president talent management",
  "sales manager",
  "co-owner",
  "cto",
  "ceo, founder",
  "assistant branch manager",
  "ceo/president",
  "dental assistant",
  "home manager",
  "owner/ceo",
  "professor",
  "chief commercial officer",
  "director of quality",
  "adjunct faculty",
  "co-founder and cto",
  "accounting controller",
  "company owner",
  "financial services representative",
  "senior director, talent management",
  "physician assistant",
  "founder and president",
  "portfolio manager",
  "associate professor",
  "director, talent acquisition",
  "real estate agent",
  "director of information technology",
  "vp, information security",
  "senior operations manager",
  "regional sales manager",
  "financial director",
  "director of recruiting",
  "director medical staff services",
  "director of finance and operations",
  "senior medical director",
  "regional operations manager",
  "principal consultant",
  "associate",
  "marketing executive",
  "dentist, practice owner",
  "associate chief medical officer",
  "principal engineer",
  "hospitalist",
  "research assistant",
  "internal medicine physician",
  "president, ceo",
  "chairman and ceo",
  "vice president of information security",
  "vp of information security",
  "chief revenue officer",
  "director information security",
  "health program manager",
  "growth marketing manager",
  "chief data officer",
  "founder and chief executive officer",
  "head of finance",
  "regional vice president",
  "president & coo",
  "business analyst",
  "director of market operations",
  "ceo / founder",
  "operations administrator",
  "customer relations manager",
  "director of information security",
  "assistant professor",
  "chief quality officer",
  "associate product manager",
  "manager, revenue operations",
  "head of sales",
  "director, medical staff services",
  "physician recruiter ",
  "head of talent management",
  "chairman & ceo",
  "clinical recruiter",
  "research director",
  "vp finance",
  "director of practice operations",
  "environmental health & safety manager",
  "hse specialist",
  "director of training and development",
  "chief nursing officer",
  "emergency physician",
  "engineering team lead",
  "chief information security officer (ciso)",
  "retail store manager",
  "medical doctor",
  "digital marketing manager",
  "director of surgical services",
  "market research executive",
  "assistant manager",
  "clinical nurse manager",
  "co-founder/ceo",
  "president and chief operating officer",
  "sr. devops engineer",
  "vice president of product development",
  "attending physician",
  "non executive director",
  "group product manager",
  "ceo/owner",
  "chief commercial officer (cco)",
  "devops engineering manager",
  "realtor",
  "head of information security",
  "office medical director",
  "family nurse practitioner",
  "research manager",
  "director of market research",
  "principal site reliability engineer",
  "brand manager",
  "vice president, marketing",
  "hr manager",
  "project support officer",
  "vice president sales",
  "sales and marketing director",
  "director of credit and collections",
  "staff engineer",
  "director market research",
  "senior software engineering manager",
  "lead dentist",
  "senior director of operations",
  "registered dental hygienist",
  "ehs coordinator",
  "demand planning manager",
  "mortgage loan officer",
  "founder ceo",
  "strategic advisor",
  "assistant vice president",
  "qhse manager",
  "commercial director",
  "chairman of the board",
  "president and coo",
  "co-founder & coo",
  "regional vice president of sales",
  "business administrator",
  "director of talent acquisition",
  "senior staff software engineer",
  "founder | ceo",
  "cmo",
  "rssi",
  "associate executive director",
  "clinic director",
  "clinic operations manager",
  "anesthesiologist",
  "vice president, talent management",
  "sre",
  "vice president, human resources",
  "market insights manager",
  "co-founder / ceo",
  "shopper marketing manager",
  "principal product manager",
  "cto & co-founder",
  "personal banker",
  "occupational health, safety, and environment manager",
  "senior scientist",
  "environmental health & safety specialist",
  "head of product marketing",
  "carer",
  "director clinical operations",
  "founder & president",
  "human resources business partner",
  "security engineer",
  "clinical assistant professor",
  "security engineering manager",
  "underwriter",
  "vice president of learning and development",
  "clinical team manager",
  "insurance coordinator",
  "tech manager",
  "market risk analyst",
  "branch manager",
  "senior director human resources",
  "executive assistant to chief executive officer",
  "head of engineering",
  "head of talent acquisition",
  "vice president of customer success",
  "resident physician",
  "director of physician recruitment",
  "sales & marketing director",
  "lead devops engineer",
  "bank teller",
  "chair",
  "associate brand manager",
  "manager, customer success",
  "senior financial analyst",
  "board of directors",
  "clinical services manager",
  "chief administrative officer (cao)",
  "clinical quality program manager",
  "analyst",
  "vice president of sales and marketing",
  "director of imaging services",
  "director of clinic operations",
  "regional manager",
  "nurse practitioner",
  "president and founder",
  "senior finance manager",
  "human resources",
  "quality manager",
  "chief strategy officer (cso)",
  "ceo / co-founder",
  "market research associate",
  "independent consultant",
  "vp of engineering",
  "head of market research",
  "family physician",
  "banking relationship specialist",
  "vice president - information security",
  "art director",
  "it project manager",
  "mortgage loan consultant",
  "clinical program manager",
  "market research ceo",
  "nurse manager",
  "relationship director",
  "senior vice president marketing",
  "program coordinator ii",
  "president/owner",
  "head of product management",
  "managing member",
  "plastic surgeon",
  "platform engineer",
  "solutions architect",
  "chief executive officer & co-founder",
  "security director",
  "owner dentist",
  "director, learning & development",
  "public health specialist",
  "founder, president & ceo",
  "senior clinical recruiter",
  "site reliability engineer ii",
  "ceo/co-founder",
  "senior accounting manager",
  "principal customer success manager",
  "associate medical director",
  "president ",
  "founding partner",
  "senior provider recruiter",
  "orthopaedic surgeon",
  "senior vice president, chief information security officer",
  "chief medical informatics officer",
  "vice president, investment banking",
  "accounting assistant",
  "at",
  "technical lead",
  "manager, talent development",
  "chief innovation officer",
  "co founder",
  "senior vice president operations",
  "senior talent acquisition specialist",
  "director data management",
  "coo/cfo",
  "hse coordinator",
  "store manager",
  "senior security engineer",
  "chief accounting officer",
  "senior customer success manager",
  "compensation manager",
  "vice president information technology",
  "insurance specialist",
  "public health consultant",
  "marketing",
  "senior staff accountant",
  "hca",
  "supervisor",
  "vice president of human resources",
  "director of rehabilitation",
  "co-chief executive officer",
  "demand planner",
  "sr. packaging engineer",
  "plant controller",
  "primary care physician",
  "intern",
  "technical integration manager",
  "dentist/ceo",
  "vice president, sales",
  "ceo and dentist",
  "head chef",
  "head of product development",
  "human resources generalist",
  "dental director",
  "senior manager, revenue operations",
  "student",
  "project program coordinator",
  "entrepreneur",
  "director data science",
  "director of case management",
  "director, finance",
  "chief executive officer & founder",
  "creative director",
  "unit manager",
  "investor",
  "iş güvenliği uzmanı",
  "senior manager, talent development",
  "visual merchandiser",
  "cofounder & ceo",
  "jefe de seguridad de la información",
  "director human resources",
  "public health nutritionist",
  "accounting bookkeeper",
  "director, market research",
  "vice president of global sales",
  "director of pharmacy",
  "director, information security",
  "president & chief operating officer",
  "owner/president",
  "director of finance and accounting",
  "executive vice president and chief financial officer",
  "pediatric dentist",
  "vp information security",
  "director of development",
  "senior vice president human resources",
  "brand director",
  "co-ceo",
  "president and ceo ",
  "senior platform engineer",
  "information security officer",
  "talent acquisition recruiter",
  "corporate recruiter",
  "group sales director",
  "director of cyber security",
  "manager of operations",
  "vice president of talent management",
  "founder & ceo ",
  "talent development program manager",
  "market research interviewer",
  "associate director, data management",
  "chief operating officer ",
  "dentist, managing clinical director",
  "orthodontist",
  "chief business officer",
  "vice president business development",
  "chief risk officer",
  "vice president, finance",
  "chief medical information officer",
  "director of quality improvement",
  "director of medical staff services",
  "director of credit & collections",
  "senior manager, market research",
  "principal ceo",
  "area operations manager",
  "assistant director",
  "financial advisor",
  "head of product design",
  "senior account executive",
  "senior director, demand generation",
  "digital product owner",
  "executive recruiter",
  "co-founder & co-ceo",
  "sr devops engineer",
  "lead site reliability engineer",
  "market research recruiter",
  "rn",
  "vice president, global talent acquisition",
  "chief development officer",
  "product director",
  "vice president ",
  "semi retired",
  "supply chain coordinator",
  "head of brand marketing",
  "financial service representative",
  "engineering leader",
  "co-founder and coo",
  "occupational safety and health specialist",
  "director of social services",
  "associate vice president",
  "resident care assistant",
  "chief brand officer",
  "quality assurance manager",
  "marketing coordinator",
  "founder and ceo ",
  "marketing specialist",
  "senior partner",
  "director, devops",
  "cofounder and ceo",
  "senior market research associate",
  "clinical professor",
  "owner and ceo",
  "surgeon",
  "public health scientist",
  "vice president, business development",
  "personal financial advisor",
  "accounting",
  "founder & cto",
  "vp marketing",
  "director of risk management",
  "senior program coordinator",
  "vice president, sales & marketing",
  "retail manager",
  "development team lead",
  "family medicine physician",
  "physician recruitment",
  "sustainability manager",
  "loan servicing specialist",
  "dentist/owner",
  "quality improvement manager",
  "director of physician services",
  "senior loan officer",
  "billing specialist",
  "disease intervention specialist ",
  "research analyst",
  "environmental, health & safety manager",
  "founding member",
  "sr. site reliability engineer",
  "director of laboratory services",
  ".",
  "team manager",
  "hsse manager",
  "cpa",
  "director of it",
  "founder - ceo",
  "director of sales and business development",
  "software architect",
  "enterprise customer success manager",
  "business development director",
  "health program coordinator",
  "public health environmentalist",
  "co-founder & president",
  "national sales director",
  "us healthcare recruiter",
  "director of brand marketing",
  "practice director",
  "director of data science",
  "quality management nurse consultant",
  "environmental health and safety",
  "finance",
  "partner ",
  "executive medical director",
  "health safety environment",
  "resourcing advisor",
  "treasurer",
  "director of technology",
  "sre manager",
  "president elect",
  "co-founder & chief executive officer",
  "president/chief executive officer",
  "vice president, customer success",
  "general dental practitioner",
  "hospital administrator",
  "senior hr business partner",
  "senior research analyst",
  "health and safety",
  "finance intern",
  "marketing communications manager",
  "programme manager",
  "business consultant",
  "chief credit officer",
  "incoming investment banking summer analyst",
  "regional chief medical officer",
  "senior associate",
  "chief executive officer and founder",
  "vice president of engineering",
  "regional human resources director",
  "director of nursing services",
  "healthcare executive",
  "director of sales and marketing",
  "financial services officer",
  "principal scientist",
  "founder/president",
  "vice president of finance and operations",
  "enterprise sales director",
  "chief sales officer (cso)",
  "director of retail marketing",
  "director of compliance",
  "accounting clerk",
  "self employed",
  "assistant medical director",
  "technical director",
  "market medical director",
  "product lead",
  "doctor",
  "pediatric hospitalist",
  "director of marketing and business development",
  "product marketing manager",
  "senior product designer",
  "insights manager",
  "responsable hse",
  "environment health safety manager",
  "recruiting manager",
  "managing clinical director",
  "mentor",
  "rgn",
  "physical therapist",
  "health & safety",
  "member board of trustees",
  "clinical nutrition manager",
  "director of environmental services",
  "general counsel",
  "chief business development officer",
  "manager of devops",
  "general surgeon",
  "market research project manager",
  "first vice president",
  "receptionist",
  "eh&s specialist",
  "chairperson",
  "senior care assistant",
  "teacher",
  "environmental, health, and safety manager",
  "surveillance epidemiologist",
  "talent",
  "data analyst",
  "project director",
  "internal medicine hospitalist",
  "director of fp&a",
  "technical account manager",
  "sr. physician recruiter",
  "senior director of talent management",
  "health advisor",
  "chief physician executive",
  "regional operations director",
  "research executive",
  "programme director",
  "clinic administrator",
  "co-founder, cto",
  "clinical associate professor",
  "vice president investment banking",
  "tech lead",
  "vice president, global information security",
  "operations leader",
  "mortgage loan processor",
  "tax director",
  "customer success associate",
  "credit manager",
  "lending specialist",
  "vp, marketing operations",
  "vice president sales and marketing",
  "ehs manager ",
  "resident doctor",
  "fellow",
  "president & founder",
  "global head of talent",
  "franchise owner",
  "vice president of technology",
  "director of analytics",
  "director of talent management ",
  "loan processor",
  "senior director, human resources",
  "small business owner",
  "chief experience officer",
  "director of communications",
  "clinical supervisor",
  "head of talent attraction",
  "territory manager",
  "senior dentist",
  "director of finance and administration",
  "co-founder and chief executive officer",
  "chief medical officer ",
  "author",
  "solicitor",
  "software development manager",
  "orthopedic surgeon",
  "senior staff engineer",
  "director - cyber security",
  "executive board member",
  "director, global talent management",
  "vice president clinical operations",
  "public health project officer",
  "adjunct instructor",
  "packaging manager",
  "teaching assistant",
  "manager, devops engineering",
  "associate recruiter",
  "corporate accounting manager",
  "cto and co-founder",
  "vp human resources",
  "assistant clinical director",
  "chief of operations",
  "facilities manager",
  "senior research manager",
  "neurosurgeon",
  "sourcing specialist",
  "practice owner",
  "principal project officer",
  "public health analyst",
  "director of investment operations",
  "group chief executive officer",
  "chief executive officer ",
  "client director",
  "chair of the board of directors",
  "director of outpatient services",
  "search consultant",
  "global sales director",
  "manager, market research",
  "payroll manager",
  "assistant packaging development manager",
  "head of security operations",
  "vice president - talent acquisition",
  "senior talent acquisition partner",
  "cio",
  "dentist/practice owner",
  "clinical quality manager",
  "chief executive officer and co-founder",
  "principal recruiter",
  "director of health services",
  "head of growth marketing",
  "care worker",
  "director of quality assurance",
  "project controller",
  "assistant product manager",
  "medical assistant",
  "executive director of operations",
  "senior advisor",
  "engagement manager",
  "it director",
  "service manager",
  "software engineering team lead",
  "sr. engineering manager",
  "public health program coordinator",
  "psychiatric mental health nurse practitioner",
  "accounting supervisor",
  "crna",
  "manager, security engineering",
  "vice president, global talent management",
  "healthcare administrator",
  "enterprise account executive",
  "human resources specialist",
  "accounts receivable manager",
  "director of research",
  "vp, performance marketing",
  "founder and cto",
  "people operations manager",
  "uk sales director",
  "public health laboratory scientist",
  "regional controller",
  "vp, talent acquisition",
  "director, security engineering",
  "human resource director",
  "board director",
  "quality management specialist",
  "treatment coordinator",
  "product delivery manager",
  "president & co-founder",
  "staff devops engineer",
  "senior program manager",
  "sr. director, talent management",
  "manager, physician recruitment",
  "chief executive",
  "president and co-founder",
  "site medical director at altamed health services",
  "incoming 2024 investment banking summer analyst",
  "financial services manager",
  "senior vice president business development",
  "senior tax accountant",
  "global ehs manager",
  "vp of sales & marketing",
  "project management officer",
  "product analyst",
  "software developer",
  "engineer",
  "scheduling specialist",
  "general partner",
  "public health nutritionist supervisor",
  "vice president - investment banking",
  "senior investment director",
  "marketing consultant",
  "director ",
  "practice manager of operations",
  "sr. hr business partner",
  "azure devops engineer",
  "financial manager",
  "vp of human resources",
  "chief customer officer",
  "business development specialist",
  "manager, software engineering",
  "director, market intelligence",
  "cfo/coo",
  "nursing manager",
  "operations supervisor",
  "ceo and founder ",
  "instructor",
  "vice president and chief financial officer",
  "volunteer",
  "medical student",
  "team product owner",
  "dermatologist",
  "manager, devops",
  "head of learning and development",
  "svp of sales",
  "director, credit & collections",
  "travel nurse recruiter",
  "senior sales director",
  "market risk manager",
  "ceo | co-founder",
  "vice president of sales & marketing",
  "founder + ceo",
  "manager package development",
  "coo & co-founder",
  "licensed nursing home administrator",
  "head of security engineering",
  "hseq manager",
  "executive vice president and chief operating officer",
  "head of data science",
  "vice president - operations",
  "general sales manager",
  "principal solutions engineer",
  "clinical research coordinator",
  "senior healthcare recruiter",
  "accounting professional",
  "market president",
  "group clinical manager",
  "accounting specialist",
  "director of emergency services",
  "owner/director",
  "co-founder, coo",
  "director, product development",
  "ehs specialist ",
  "talent management",
  "director, data science",
  "director of medical records",
  "vice chair",
  "operations executive",
  "member, board of directors",
  "member of the board of advisors",
  "director of admissions",
  "scientist",
  "housekeeper",
  "director of digital marketing",
  "public health program associate",
  "recruitment specialist",
  "clinical coordinator",
  "regional stores director",
  "co-founder ",
  "district manager",
  "clinical pharmacy manager",
  "clinical psychologist",
  "director of patient care services",
  "accounts payable specialist",
  "support worker",
  "director of professional services",
  "health, safety, and environmental manager",
  "public health medical officer",
  "director of financial operations",
  "investment banking vice president",
  "talent management lead",
  "solicitor and partner",
  "store group manager",
  "sr. software engineer",
  "supply chain director",
  "director of marketing and communications",
  "head of human resources",
  "global head of research",
  "finance operations manager",
  "senior manager, software engineering",
  "nurse",
  "senior financial services representative",
  "director of product",
  "compliance manager",
  "ceo/administrator",
  "digital product manager",
  "cyber security manager",
  "physician recruitment manager",
  "recruitment manager",
  "social media manager",
  "accounting intern",
  "vp product development",
  "qa manager",
  "director of behavioral health services",
  "director of growth marketing",
  "director of radiology",
  "health, safety & environmental manager",
  "director of patient services",
  "mortgage loan originator",
  "ceo and cofounder",
  "v.p. of operations",
  "c.e.o",
  "executive vice president of operations",
  "dentist, ceo",
  "chief legal officer",
  "public health epidemiologist",
  "business development",
  "delivery manager",
  "rehab director",
  "data scientist",
  "faculty",
  "vice president, branch manager",
  "sales and marketing specialist",
  "president/founder",
  "incoming investment banking analyst",
  "deputy chief executive officer",
  "ceo | founder",
  "managing principal",
  "clinician",
  "director of software engineering",
  "ehs supervisor",
  "senior finance business partner",
  "sales development representative",
  "chief executive officer and president",
  "director, growth marketing",
  "director, cyber security services",
  "senior director of marketing",
  "global marketing director",
  "vice president sales & marketing",
  "executive talent acquisition partner",
  "digital marketing specialist",
  "president/coo",
  "head of it security",
  "head of customer success",
  "group cfo",
  "ceo/ founder",
  "senior sre",
  "credit analyst",
  "vice president marketing operations",
  "senior solutions engineer",
  "director of quality management",
  "head of procurement",
  "owner & ceo",
  "assistant vice president, information security",
  "chef",
  "financial coordinator",
  "internal medicine resident physician",
  "director, credit",
  "clinical administrator",
  "professional recruiter",
  "health, safety and environmental manager",
  "manager packaging development",
  "director of human resources ",
  "founder & managing partner",
  "teller supervisor",
  "head of design",
  "retired ceo",
  "managing dentist",
  "dental hygienist",
  "chief transformation officer",
  "executive",
  "associate director, data science",
  "growth marketing",
  "deputy general manager",
  "dentist, practice owner at aspen dental",
  "nursing home administrator",
  "principal owner",
  "director, learning and development",
  "credit officer",
  "finance business partner",
  "patient care coordinator",
  "professor of medicine",
  "vice president, controller",
  "director of marketing operations",
  "provider recruitment manager",
  "head of business development",
  "vp business development",
  "independent director",
  "business development executive",
  "area vice president of sales",
  "executive vice president & chief operating officer",
  "sr. market research analyst",
  "product designer",
  "founder & owner",
  "cofounder",
  "security innovation principal director",
  "",
  "doctor of dental medicine",
  "accounts payable manager",
  "senior public health nutritionist",
  "founder & managing director",
  "director, business development",
  "universal banker",
  "environmental health & safety",
  "co-founder and president",
  "maintenance controller",
  "senior data engineer",
  "vp, chief information security officer",
  "medical director ",
  "senior data scientist",
  "director of growth",
  "marketing assistant",
  "hedge fund manager",
  "associate administrator",
  "executive chairman",
  "sr. director, human resources",
  "laboratory director",
  "head of information technology",
  "licensed realtor",
  "researcher",
  "ceo - founder",
  "director of sustainability",
  "hse manager ",
  "c.e.o.",
  "data engineering manager",
  "senior vice president finance",
  "director of market intelligence",
  "accounting associate",
  "v.p. operations",
  "director, practice operations",
  "senior director of demand generation",
  "security architect",
  "director of medical services",
  "unemployed",
  "site manager",
  "system administrator",
  "manager of talent development",
  "physician recruitment specialist",
  "director, cyber security",
  "vp of product development",
  "controller ",
  "head of quantitative research",
  "devops team leader",
  "clinical nurse coordinator",
  "chief nurse executive",
  "chief financial officer (cfo)",
  "nursing administrator",
  "chief program officer",
  "head of growth",
  "director, data management",
  "senior managing director",
  "district medical director",
  "director of sales & marketing",
  "procurement manager",
  "interim ceo",
  "technical architect",
  "director, marketing",
  "senior director, talent acquisition",
  "security associate director",
  "engineering manager at virgin pulse",
  "senior talent management specialist",
  "division controller",
  "director of account management",
  "head of compliance",
  "chief executive officer, founder",
  "group finance director",
  "ceo / president",
  "health care recruiter",
  "executive administrator",
  "packaging designer",
  "chairman and chief executive officer",
  "engineering manager at venmo",
  "talent management ",
  "senior controller",
  "founder and managing partner",
  "dental consultant",
  "founder & director",
  "sr. loan officer",
  "human resources coordinator",
  "assistant vice president, talent acquisition",
  "cyber security engineer",
  "credit director",
  "global controller",
  "behavioral health director",
  "vice president of clinical services",
  "assistant vice president - information security",
  "business development representative",
  "human resources assistant",
  "vp of customer success",
  "sr. product manager",
  "purchasing manager",
  "secretary",
  "business intelligence developer",
  "vice president, marketing operations",
  "child and adolescent psychiatrist",
  "office administrator",
  "vice president, chief information security officer",
  "technical manager",
  "director of pharmacy services",
  "director of client services",
  "product management",
  "vp of devops",
  "chief sales officer",
  "staff psychiatrist",
  "ceo & cofounder",
  "senior director, information security",
  "sustainability director",
  "territory director of operations",
  "district operations manager",
  "devops engineer ii",
  "senior frontend engineer",
  "vp branch manager",
  "lead product manager",
  "talent development specialist",
  "senior sales engineer",
  "ehs program manager",
  "senior solutions consultant",
  "health care assistant",
  "manager ehs",
  "partner and solicitor",
  "executive vice president of sales",
  "aws devops engineer",
  "director of medical surgical services",
  "president & cfo",
  "executive member",
  "associate site reliability engineer",
  "medical office director",
  "producer",
  "undergraduate research assistant",
  "senior director of engineering",
  "home admissions advisor",
  "vice president, product development",
  "co-founder, president",
  "client services manager",
  "licensed real estate agent",
  "prosthodontist",
  "director market intelligence",
  "chief operating officer (coo)",
  "founder and executive director",
  "case manager",
  "director, business operations",
  "vice president of product",
  "board advisor",
  "vp of technology",
  "director physician recruitment",
  "director of training",
  "director of physician recruiting",
  "vice president & general manager",
  "director of community relations",
  "sr. human resources business partner",
  "staff accountant at lutz",
  "customer service representative",
  "chief executive officer / founder",
  "adjunct assistant professor",
  "vice president of talent acquisition",
  "marketing professional",
  "director of operations ",
  "cloud devops engineer",
  "independent contractor",
  "talent acquisition coordinator",
  "technology manager",
  "property litigation partner",
  "senior director of finance",
  "senior corporate recruiter",
  "billing manager",
  "pharmacy operations manager",
  "principal learning consultant",
  "devops architect",
  "behavioral health program manager",
  "software engineer intern",
  "radiologist",
  "environmental, health & safety specialist",
  "senior business development manager",
  "sr. manager, talent management",
  "president of the board of directors",
  "therapist",
  "operating partner",
  "lifestyle coordinator",
  "senior packaging development manager",
  "director of clinical operations ",
  "global sustainability manager",
  "chief accounting officer (cao)",
  "executive advisor",
  "founder and medical director",
  "lead recruiter",
  "avp, talent acquisition",
  "senior practice administrator",
  "group ceo",
  "vp of business development",
  "senior vice president - information security",
  "hospital ceo",
  "director of product marketing",
  "associate director of operations",
  "ehs project manager",
  "public health microbiologist",
  "clinical operations director",
  "co-founder & chief operating officer",
  "division chief medical officer",
  "senior office manager",
  "adult nurse practitioner",
  "national sales manager",
  "hse",
  "member of the board of directors",
  "epidemiologist",
  "senior director, growth marketing",
  "chief clinical operations officer",
  "lead software engineer",
  "director of plant operations",
  "quality development manager",
  "director operations",
  "promotions coordinator",
  "chief compliance officer",
  "dentist and practice owner",
  "senior buyer",
  "technical program manager",
  "physician liaison",
  "undergraduate researcher",
  "strategy consultant",
  "chief executive officer (ceo)",
  "staff registered nurse",
  "executive director, talent management",
  "r&d director",
  "public health sanitarian",
  "senior engineer",
  "sales director emea",
  "executive director, talent acquisition",
  "sr. market research manager",
  "public health social worker",
  "vp, talent management",
  "chief dental officer",
  "data engineer",
  "director of provider recruitment",
  "staff sre",
  "emergency medical technician",
  "credit risk director",
  "cfo / coo",
  "human resources professional",
  "founder/ ceo",
  "public health nutrition program director",
  "data quality manager",
  "ceo & co-founder ",
  "m.d.",
  "engineering manager, devops",
  "release manager",
  "director of customer success",
  "site director",
  "senior vice president, marketing",
  "sales consultant",
  "trauma medical director",
  "senior vice president of global sales",
  "eh&s coordinator",
  "senior physician recruiter ",
  "vice president, investment team",
  "marketing planning manager",
  "director of marketing ",
  "local director",
  "talent acquisition consultant ii",
  "director of sales operations",
  "vice president of strategic sales",
  "engineering manager at smartthings",
  "vice president global marketing",
  "senior credit analyst",
  "sr. project manager",
  "co-founder | ceo",
  "vice president of clinical operations",
  "marketing campaign manager",
  "fp&a manager",
  "ambassador",
  "sustainability officer",
  "founder and managing director",
  "vice president information technology and security",
  "product development",
  "head of healthcare",
  "virtual medical director",
  "director of people operations",
  "market risk specialist",
  "director, practice development",
  "investment manager",
  "head of pmo",
  "incoming 2023 investment banking summer analyst",
  "devops tech lead",
  "senior brand manager",
  "public health nutrition consultant",
  "operations support manager",
  "clinical practice manager",
  "regional vice president of operations",
  "senior product marketing manager",
  "provider sourcing specialist",
  "vice president enterprise sales",
  "sales associate",
  "vice president of sales operations",
  "chief talent officer",
  "mental health therapist",
  "executive vice president of finance",
  "branch director",
  "paramedic",
  "co-founder and chief technology officer",
  "vice president, learning and development",
  "senior clinical studies coordinator",
  "vice president sales operations",
  "area ehs manager",
  "client success manager",
  "director board of directors",
  "team lead manager",
  "managing director, investment banking",
  "vice president, information security management",
  "director of procurement",
  "devops lead",
  "commercial manager",
  "insurance claims specialist",
  "senior growth marketing manager",
  "physician assistant ",
  "president ceo",
  "senior talent development manager",
  "litigation partner",
  "retail director",
  "food service director",
  "vp, global talent acquisition",
  "vice president, it & security",
  "clinical advisor",
  "cloud engineering manager",
  "director of dining services",
  "teller",
  "certified registered nurse anesthetist",
  "director of client success",
  "director devops",
  "patient access director",
  "social worker",
  "certified financial specialist",
  "accounting analyst",
  "sales executive",
  "loan officer assistant",
  "founding engineer",
  "fund controller",
  "chief development officer (cdo)",
  "financial representative",
  "care home manager",
  "health & safety specialist",
  "director quality management",
  "vp of product",
  "managing director investment banking",
  "chief technical officer",
  "head of product & design",
  "strategic business consultant iii",
  "it operations manager",
  "senior account manager",
  "medical director, behavioral health services",
  "lecturer",
  "investment vice president",
  "founder and director",
  "clinic director at family health centers of san diego",
  "interventional cardiologist",
  "cto, co-founder",
  "brand ambassador",
  "trade development manager",
  "domestic",
  "cost accounting manager",
  "chief behavioral health officer",
  "director of talent acquisition ",
  "platform engineering manager",
  "vp of performance marketing",
  "vice president, senior investment advisor",
  "vice president, information security manager",
  "associate chief medical information officer",
  "public health program specialist",
  "digital marketing director",
  "director of sales marketing",
  "executive director/ceo",
  "commercial loan officer",
  "ceo, president",
  "business office manager",
  "senior devops manager",
  "co-founder, president & ceo",
  "assistant clinical professor",
  "senior backend engineer",
  "provider recruiter ii",
  "project coordinator",
  "information security analyst",
  "inventory controller",
  "independent business owner",
  "vp, operations",
  "director packaging development",
  "sous chef",
  "accreditation manager",
  "corporate financial controller",
  "regional medical director at altamed health services",
  "international sales director",
  "ceo, dentist",
  "developer advocate",
  "chief executive officer and board member",
  "summer intern",
  "svp",
  "assistant professor of medicine",
  "clinical instructor",
  "market research assistant",
  "relationship officer",
  "certified medical assistant",
  "director, customer success",
  "director, credit and collections",
  "medical secretary",
  "public health laboratory scientist iii",
  "market research contractor",
  "group ciso",
  "clinical resource manager",
  "chairman, president & ceo",
  "founder, chairman & ceo",
  "vp sales operations",
  "provider recruiter ",
  "senior underwriter",
  "environment health and safety manager",
  "physician advisor",
  "environmental, health and safety specialist",
  "product specialist",
  "environment, health and safety",
  "physician & provider recruiter",
  "pharmacist",
  "talent management consultant",
  "founder ",
  "research scientist",
  "systems administrator",
  "founder and chief medical officer",
  "associate investment director",
  "licensed clinical social worker",
  "c.o.o.",
  "associate program director",
  "vp of talent management",
  "regional program manager",
  "senior business analyst",
  "director business development",
  "security consulting senior manager",
  "care manager",
  "director of benefits",
  "accounting coordinator",
  "manager, ehs",
  "clinical case manager",
  "relationship banker",
  "technical product owner",
  "head of brand",
  "design manager",
  "pricing manager",
  "rn clinical manager",
  "property accountant",
  "sr. manager, revenue operations",
  "group marketing manager",
  "community manager",
  "director of security engineering",
  "legal director",
  "product development specialist",
  "vice president of devops",
  "sr. loan processor",
  "vp, controller",
  "senior android engineer",
  "owner/dentist",
  "vice president, people",
  "financial service officer",
  "senior manager, devops",
  "head of commercial finance",
  "facility medical director",
  "public health advisor",
  "medical staff recruiter",
  "sr. manager, talent development",
  "sr. director, performance marketing",
  "head of cyber security",
  "director of rehabilitation services",
  "assistant accounting manager",
  "business office director",
  "physician/provider recruiter",
  "public health officer",
  "director of innovation",
  "co-founder & managing director",
  "vice president, clinical operations",
  "data center security manager",
  "head of global talent management",
  "research intern",
  "environmental health program manager",
  "senior software engineer team lead",
  "engineering manager - devops",
  "production controller",
  "executive director ",
  "chief medical director",
  "public health nurse consultant",
  "vice president, investment research",
  "strategic customer success manager",
  "financial consultant",
  "responsable qse",
  "director of credit administration",
  "senior associate, market research",
  "vice president - marketing",
  "safety manager",
  "director of strategy",
  "principal devops engineer",
  "senior research executive",
  "director of operations and business development",
  "chief accountant",
  "solutions engineer",
  "director, application security",
  "senior clinical manager",
  "operations coordinator",
  "senior director of product management",
  "devops director",
  "state public health veterinarian",
  "cfo ",
  "senior recruitment consultant",
  "executive vice president, chief operating officer",
  "senior manager revenue operations",
  "patient care technician",
  "site medical director",
  "director program management",
  "board chair",
  "department chair",
  "director of financial planning",
  "vice president - devops",
  "program coordinator i",
  "senior ehs coordinator",
  "realtor®",
  "sales",
  "banker",
  "project development manager",
  "division manager",
  "fund manager",
  "personal assistant",
  "sr. revenue operations manager",
  "sr. accountant",
  "vice president branch manager",
  "associate scientist",
  "ems medical director",
  "r&d manager",
  "real estate investor",
  "recruiting coordinator",
  "practice manager ii",
  "head of sustainability",
  "human resources administrator",
  "executive administrative assistant",
  "founder, president and ceo",
  "associate director, talent acquisition",
  "safety specialist",
  "head of sales operations",
  "senior programme manager",
  "country manager",
  "clinician recruiter",
  "client partner",
  "talent acquisition lead",
  "accounts receivable specialist",
  "fp&a analyst",
  "senior revenue operations manager",
  "market research analyst ii",
  "co-founder & ceo ",
  "freelance writer",
  "cosmetic dentist",
  "director of credit operations",
  "director of therapy operations",
  "sustainability engineer",
  "vice president devops",
  "sr. director human resources",
  "vice president of accounting",
  "director of clinical quality",
  "utilization review nurse",
  "rmn",
  "it infrastructure manager",
  "administrator/ceo",
  "bank manager",
  "ceo + founder",
  "division ehs manager",
  "director, risk adjustment",
  "chief architect",
  "manager of clinical operations",
  "dental student",
  "physician assistant at neighborhood healthcare",
  "senior director, global marketing",
  "executive officer",
  "director of data management",
  "operational director",
  "director of technical operations",
  "v.p. finance",
  "assistant buyer",
  "market research supervisor",
  "vp, branch manager",
  "vp, sales",
  "director, investment banking",
  "avp",
  "product strategy manager",
  "director surgical services",
  "vice president - information security management",
  "senior manager, business operations",
  "senior brand marketing manager",
  "vp - information security",
  "vascular surgeon",
  "president, founder",
  "director of network operations",
  "territory sales manager",
  "regional hr director",
  "finance and accounting manager",
  "customer service manager",
  "nursing supervisor",
  "marketing operations manager",
  "senior manager of revenue operations",
  "vice president of marketing operations",
  "director at tarzana treatment centers",
  "sr. accounting manager",
  "clinical research manager",
  "senior business operations manager",
  "independent distributor",
  "associate director data science",
  "senior health program coordinator",
  "cfo & co-founder",
  "registered dental assistant",
  "staff platform engineer",
  "director, physician recruitment",
  "clinical research associate",
  "partner and head of litigation",
  "chairman & chief executive officer",
  "council member",
  "corporate finance partner",
  "sr. talent management specialist",
  "client executive",
  "designer",
  "director at stanislaus county",
  "senior clinic director at altamed health services",
  "activities coordinator",
  "chief supply chain officer",
  "investment banking summer analyst",
  "senior manager information security",
  "senior ios engineer",
  "market chief executive officer",
  "aspp",
  "group sales and marketing director",
  "director, product security",
  "registered manager",
  "it service manager",
  "growth marketing manager at madison reed",
  "manager market research",
  "court production order analyst",
  "head of product security",
  "sr. financial analyst",
  "director, talent management ",
  "information technology security manager",
  "executive vice president & chief financial officer",
  "associate director, securitised products group",
  "director of packaging",
  "dentist, managing clinical director at aspen dental",
  "senior manager market research",
  "billing coordinator",
  "partner & solicitor",
  "service delivery manager",
  "trustee",
  "operations department manager",
  "senior teller",
  "director of health information management",
  "chief",
  "head of legal",
  "podcast host",
  "official member",
  "sr. director, demand generation",
  "vp, learning & development",
  "engineering manager at acquia",
  "marketing strategist",
  "hses manager",
  "vice president, sales and marketing",
  "vice president of sales, north america",
  "managing clinical dentist",
  "manager, talent acquisition",
  "growth at headway",
  "human resources analyst",
  "executive vice president business development",
  "life coach",
  "senior solutions architect",
  "health safety environment supervisor",
  "director, devops engineering",
  "deputy chief medical officer",
  "educator",
  "ct technologist",
  "private practice",
  "market research coordinator",
  "national account manager",
  "president and chief executive officer ",
  "clinic manager ii",
  "founder and chairman",
  "senior vice president and chief medical officer",
  "ehs engineer",
  "senior vice president information security",
  "professor of surgery",
  "advanced practice nurse",
  "director total rewards",
  "research associate",
  "hospital & health care professional",
  "senior demand planner",
  "manager of accounting",
  "assistant director of talent management",
  "orthodontic assistant",
  "medical practice manager",
  "staff security engineer",
  "finance officer",
  "health program manager ii",
  "interim chief medical officer",
  "regional marketing manager",
  "environmental health safety specialist ii",
  "ceo/cfo",
  "vice president customer experience",
  "vp of sales and marketing",
  "human resources executive",
  "server",
  "senior search consultant",
  "senior designer",
  "content creator",
  "director investment banking",
  "director of clinical informatics",
  "director, master data management",
  "agency owner",
  "president and owner",
  "comptroller",
  "owner and founder",
  "group vice president",
  "physician assistant certified",
  "game producer",
  "medical director of behavioral health",
  "ceo & founder ",
  "director, executive talent acquisition",
  "property manager",
  "senior technical support engineer",
  "head of infrastructure",
  "director of hr",
  "hseq coordinator",
  "division director",
  "vice president, performance marketing",
  "vice chair board of directors",
  "responsable qhse",
  "mcd dentist",
  "incoming summer analyst",
  "banking relationship specialist ",
  "population health manager",
  "devops teamlead",
  "endodontist",
  "founder & medical director",
  "senior developer",
  "early childhood educator",
  "director, data governance",
  "director, talent acquisition - north america ",
  "production manager",
  "business operations analyst",
  "chief of medicine",
  "fraud specialist",
  "vp customer success",
  "director, brand marketing",
  "human resources recruiter",
  "division president",
  "environmental, health and safety",
  "global head of talent ",
  "senior market research consultant",
  "head of performance marketing",
  "director, global package development",
  "president & ceo ",
  "deputy chief information security officer",
  "registered dietitian",
  "him director",
  "european sales director",
  "senior mortgage loan officer",
  "director of global talent management",
  "vice president of product management",
  "vice president of growth",
  "responsable devops",
  "director, credit research",
  "senior manager, talent management",
  "intake manager",
  "chapter president",
  "clinical care manager",
  "chro",
  "director of r&d",
  "cloud security architect",
  "vice president, growth marketing",
  "director of credit research",
  "marketing analyst",
  "lead data scientist",
  "retired ",
  "vice president of information technology and security",
  "director of recruitment",
  "market manager",
  "graduate research assistant",
  "senior vice president of sales and marketing",
  "technical consultant",
  "professor and chair",
  "nurse administrator",
  "vp, customer success",
  "team lead devops",
  "co-founder / cto",
  "regional president",
  "co-founder and chief medical officer",
  "senior vice president, global information security",
  "president & cto",
  "medical scribe",
  "mortgage underwriter",
  "interim chief executive officer",
  "principal investigator",
  "consultant solicitor",
  "clinic administrator at northeast valley health corporation",
  "product proposition manager",
  "sr. director, talent acquisition",
  "licensed clinical psychologist",
  "head of trading",
  "founder, chairman and ceo",
  "benefits manager",
  "assistant director of clinical services",
  "venture partner",
  "project accountant",
  "vice president of medical affairs",
  "director, provider recruitment",
  "lead business analyst",
  "owner, ceo",
  "sr. director",
  "senior research associate",
  "payroll administrator",
  "director, credit & asset management",
  "operational support manager",
  "director talent development",
  "equity partner",
  "public health advisor/project officer",
  "senior portfolio manager",
  "senior vice president, investment manager",
  "environmental, health & safety",
  "research and development scientist",
  "health care recruiter ",
  "sr. manager",
  "occupational safety & health specialist",
  "senior sales manager",
  "vice chairman",
  "physician at vista community clinic",
  "interim medical director",
  "director, benefits",
  "dentist, practice owner ",
  "deputy chief investment officer",
  "head of analytics",
  "sr. devops manager",
  "avp, talent acquisition consultant",
  "ceo & owner",
  "private banking officer",
  "cheif operating officer",
  "assistant corporate controller",
  "hr coordinator",
  "vice president, sales operations",
  "people support manager",
  "senior loan processor",
  "associate director talent management",
  "clinical pharmacist",
  "certified public accountant",
  "acting ceo",
  "co-founder & cpo",
  "information security architect",
  "chief science officer",
  "director of district operations",
  "director of ancillary services",
  "scrum master",
  "ceo and chairman",
  "vice president - finance",
  "vp sales and marketing",
  "human resources assistant at salud para la gente",
  "chief health equity officer",
  "recruiter ii",
  "executive consultant",
  "vice president, total rewards",
  "director patient financial services",
  "area vice president",
  "center administrator",
  "senior manager, marketing operations",
  "director of customer service",
  "board trustee",
  "talent acquisition",
  "vp sales",
  "head of customer service",
  "senior vice president of business development",
  "pharmacy technician",
  "chief medical officer and co-founder",
  "senior manager talent acquisition",
  "assistant director of nursing",
  "marketing intern",
  "director of facilities management",
  "information technology project manager",
  "senior human resources generalist",
  "director of financial reporting",
  "behavioral health medical director",
  "executive manager",
  "cso",
  "cabin manager",
  "chief operational officer",
  "vice president and general manager",
  "director, national accounts",
  "vp of growth",
  "superintendent",
  "relationship manager",
  "vice president, corporate controller",
  "co-founder + ceo",
  "chief procurement officer",
  "senior director of information security",
  "director, performance marketing",
  "ceo and owner",
  "director, operations",
  "head of product and engineering",
  "emergency department medical director",
  "chief financial officer & treasurer",
  "clinical lead",
  "data analytics manager",
  "public health assistant",
  "engineering manager at printify"
]

export const LOCATION = [
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Bermuda",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Burundi",
  "Cambodia",
  "Canada",
  "Cayman Islands",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hong Kong SAR",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kosovo",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Liberia",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Nigeria",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Papua New Guinea",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "The Bahamas",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Venezuela",
  "Vietnam",
  "Zambia",
  "Zimbabwe"
]