import React from "react";
import { Badge, Text } from "@mantine/core";

type PropsType = {};

export default function GeneratedByAI(props: PropsType) {
  return (
    <Text mt="lg" align="right" size="xs" opacity={0.5}>
      Generated by artificial intelligence. 🤖
    </Text>
  );
}
